### PR TITLE
Update README

### LINKED ISSUE #65: Update README

### PR DESCRIPTION
**Pull request by astropenguin**
Closes #65.

### CODE REVIEW

**Review by nasatoya — COMMENTED** [review]
I think line 99 is path_marged, not path_weather, but the rest is good.

**Comment by astropenguin** [comment]
@nasatoya Thank you for finding the wrong line! I will fix it soon.

**Review by nasatoya — APPROVED** [review]
Looks good to me!

**Review by kiwakami — APPROVED** [review]
I think it's good!

**Pull request merged**
