### PR TITLE
Add script for merge 

### LINKED ISSUE #104: Add script for merging specified zarr files
Add a script for merging the specified zarr files and returning a zip file.

### PR DESCRIPTION
**Pull request by kiwakami**
Closed #104.
Add script for merging zarr files and returning zip files.

### CODE REVIEW

**Review by astropenguin — COMMENTED** [review]
Thank you for the update! Could you please check the following codes?

```python
for corr in (DATA / "correlator").glob("*")
```

It will extract all files in the correlator directory (both `.zarr` and `.dist.zarr`).

```python
correlator.convert(corr, overwrite=True)
```

Do we still need this?

**Comment by kiwakami** [comment]
Thank you for your comment!
- I thought I was using NAME_FMT_CORR to specify *dist.zarr, but I realized that the for statement loops in vain, so I fixed it.
- I noticed that `correlator.convert(corr, overwrite=True)`is not necessary.

**Review by astropenguin — COMMENTED** [review]
Thank you for the update. One more thing I noticed is that the path of the power meter Zarr specifies not a concatenated one but a specific measurement? If it is OK, please let me know and I will approve your PR!

**Comment by kiwakami** [comment]
Thank you. Power meter zarr `WP7.6_2022144230000.zarr` includes all time data, so there is no problem.

**Review by astropenguin — APPROVED** [review]

**Pull request merged**
